# Clippy リント設定
# 注意: allow, warn, deny などのリントレベルは Cargo.toml で設定します

# カスタム設定
avoid-breaking-exported-api = false
cognitive-complexity-threshold = 30
max-fn-params-bools = 3
max-struct-bools = 3
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
too-many-arguments-threshold = 7
too-many-lines-threshold = 100
array-size-threshold = 512000
vec-box-size-threshold = 4096

# ドキュメント関連
missing-docs-in-crate-items = true

# テスト関連
allow-unwrap-in-tests = true
