# Rust 2024 エディション向け rustfmt 設定

# 基本設定
edition = "2024"
style_edition = "2024"

# インデント設定
tab_spaces = 4
hard_tabs = false

# 行の長さ
max_width = 100
comment_width = 80
wrap_comments = true

# 改行設定
newline_style = "Unix"
use_small_heuristics = "Default"

# インポート設定
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# フォーマット設定
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_code_in_doc_comments = true

# スペース設定
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false

# その他の設定
use_field_init_shorthand = true
use_try_shorthand = true
normalize_comments = true
normalize_doc_attributes = true
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0

# エラー処理
error_on_line_overflow = false
error_on_unformatted = false

# 構造体・列挙型
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20

# 関数
fn_single_line = false
where_single_line = false

# 条件式
control_brace_style = "AlwaysSameLine"

# チェーン呼び出し
chain_width = 60
single_line_if_else_max_width = 50
