# User Service Configuration Example
# このファイルをコピーして user-service.yaml として使用してください

server:
  host: "0.0.0.0"
  port: 50051

database:
  url: "postgres://user:password@localhost:5432/effect_user"
  max_connections: 10

auth:
  type: "mock"
  # Mock認証用の事前定義トークン（オプション）
  predefined_tokens:
    - token: "dev-token-123"
      user_id: "user-1"
    - token: "test-token-456"
      user_id: "user-2"

# Firebase認証を使用する場合
# auth:
#   type: "firebase"
#   project_id: "your-firebase-project-id"
#   service_account_key_path: "/path/to/service-account-key.json"

event:
  type: "memory"

# Google Pub/Subを使用する場合
# event:
#   type: "pubsub"
#   project_id: "your-gcp-project-id"
#   topic_name: "user-events"
