[package]
name = "shared_security"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
jsonwebtoken = "9"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
uuid = { version = "1.11", features = ["v4", "serde"] }
