[package]
name = "shared_database"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = [
  "runtime-tokio-native-tls",
  "postgres",
  "json",
  "chrono",
  "uuid",
] }
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
