[package]
name = "shared_repository"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio-native-tls",
  "postgres",
  "json",
  "chrono",
  "uuid",
] }
thiserror = "2.0"
uuid = { version = "1.11", features = ["v4", "serde"] }
hex = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
